---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erhudy-test-1
  namespace: namespace-1
  annotations:
    kairos.erhudy.com/cron-pattern: "* * * * *"
spec:
  selector:
    matchLabels:
      app: erhudy-test-1
  template:
    metadata:
      labels:
        app: erhudy-test-1
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erhudy-test-2
  namespace: namespace-1
  annotations:
    kairos.erhudy.com/cron-pattern: "*/3 * * * *"
spec:
  selector:
    matchLabels:
      app: erhudy-test-2
  template:
    metadata:
      labels:
        app: erhudy-test-2
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: erhudy-test-3
  namespace: namespace-1
  annotations:
    kairos.erhudy.com/cron-pattern: "*/4 * * * *"
spec:
  selector:
    matchLabels:
      app: erhudy-test-3
  template:
    metadata:
      labels:
        app: erhudy-test-3
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erhudy-test-4
  namespace: namespace-2
  annotations:
    kairos.erhudy.com/cron-pattern: "*/2 * * * *"
spec:
  selector:
    matchLabels:
      app: erhudy-test-4
  template:
    metadata:
      labels:
        app: erhudy-test-4
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erhudy-test-5
  namespace: namespace-2
  annotations:
    kairos.erhudy.com/cron-pattern: "*/2 * * * *"
spec:
  selector:
    matchLabels:
      app: erhudy-test-5
  template:
    metadata:
      labels:
        app: erhudy-test-5
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: erhudy-test-6
  namespace: namespace-2
  annotations:
    kairos.erhudy.com/cron-pattern: "* * * * *"
spec:
  selector:
    matchLabels:
      app: erhudy-test-6
  template:
    metadata:
      labels:
        app: erhudy-test-6
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]