---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erhudy-test-every-minute
  namespace: namespace-1
  annotations:
    kairos.erhudy.com/cron-pattern: "* * * * *"
  labels:
    kairos-test: "true"
spec:
  selector:
    matchLabels:
      app: erhudy-test-every-minute
      kairos-test: "true"
  template:
    metadata:
      labels:
        app: erhudy-test-every-minute
        kairos-test: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erhudy-test-every-three-minutes
  namespace: namespace-1
  annotations:
    kairos.erhudy.com/cron-pattern: "*/3 * * * *"
  labels:
    kairos-test: "true"
spec:
  selector:
    matchLabels:
      app: erhudy-test-every-three-minutes
      kairos-test: "true"
  template:
    metadata:
      labels:
        app: erhudy-test-every-three-minutes
        kairos-test: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: erhudy-test-every-four-minutes
  namespace: namespace-1
  annotations:
    kairos.erhudy.com/cron-pattern: "*/4 * * * *"
  labels:
    kairos-test: "true"
spec:
  selector:
    matchLabels:
      app: erhudy-test-every-four-minutes
      kairos-test: "true"
  template:
    metadata:
      labels:
        app: erhudy-test-every-four-minutes
        kairos-test: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erhudy-test-semicolon-every-odd-minute
  namespace: namespace-1
  annotations:
    kairos.erhudy.com/cron-pattern: "1,3,5,7,9 * * * *; 11,13,15,17,19 * * * *; 21,23,25,27,29 * * * *; 31,33,35,37,39 * * * *; 41,43,45,47,49 * * * *; 51,53,55,57,59 * * * *;"
  labels:
    kairos-test: "true"
spec:
  selector:
    matchLabels:
      app: erhudy-test-semicolon-every-odd-minute
      kairos-test: "true"
  template:
    metadata:
      labels:
        app: erhudy-test-semicolon-every-odd-minute
        kairos-test: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Namespace
metadata:
  name: namespace-2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erhudy-test-every-even-minute
  namespace: namespace-2
  annotations:
    kairos.erhudy.com/cron-pattern: "*/2 * * * *"
  labels:
    kairos-test: "true"
spec:
  selector:
    matchLabels:
      app: erhudy-test-every-even-minute
      kairos-test: "true"
  template:
    metadata:
      labels:
        app: erhudy-test-every-even-minute
        kairos-test: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erhudy-test-every-fifth-minute
  namespace: namespace-2
  annotations:
    kairos.erhudy.com/cron-pattern: "*/5 * * * *"
  labels:
    kairos-test: "true"
spec:
  selector:
    matchLabels:
      app: erhudy-test-every-fifth-minute
      kairos-test: "true"
  template:
    metadata:
      labels:
        app: erhudy-test-every-fifth-minute
        kairos-test: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: erhudy-test-every-minute
  namespace: namespace-2
  annotations:
    kairos.erhudy.com/cron-pattern: "* * * * *"
  labels:
    kairos-test: "true"
spec:
  selector:
    matchLabels:
      app: erhudy-test-every-minute
      kairos-test: "true"
  template:
    metadata:
      labels:
        app: erhudy-test-every-minute
        kairos-test: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erhudy-test-semicolon-every-odd-minute
  namespace: namespace-2
  annotations:
    kairos.erhudy.com/cron-pattern: "1,3,5,7,9 * * * *; 11,13,15,17,19 * * * *; 21,23,25,27,29 * * * *; 31,33,35,37,39 * * * *; 41,43,45,47,49 * * * *; 51,53,55,57,59 * * * *;"
  labels:
    kairos-test: "true"
spec:
  selector:
    matchLabels:
      app: erhudy-test-semicolon-every-odd-minute
      kairos-test: "true"
  template:
    metadata:
      labels:
        app: erhudy-test-semicolon-every-odd-minute
        kairos-test: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: erhudy-test-semicolon-every-odd-minute-with-timezone
  namespace: namespace-2
  annotations:
    kairos.erhudy.com/cron-pattern: "TZ=America/New_York 11,13,15,17,19 12 * * *; TZ=America/New_York 21,23,25,27,29 12 * * *; TZ=America/New_York 31,33,35,37,39 12 * * *; TZ=America/New_York 41,43,45,47,49 12 * * *; TZ=America/New_York 51,53,55,57,59 12 * * *; TZ=America/New_York 1,3,5,7,9 12 * * *;"
  labels:
    kairos-test: "true"
spec:
  selector:
    matchLabels:
      app: erhudy-test-semicolon-every-odd-minute
      kairos-test: "true"
  template:
    metadata:
      labels:
        app: erhudy-test-semicolon-every-odd-minute
        kairos-test: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: erhudy-test-more-timezones
  namespace: namespace-2
  annotations:
    kairos.erhudy.com/cron-pattern: "TZ=America/New_York 0 16 * * *; TZ=America/New_York 12 18 3 * *" 
  labels:
    kairos-test: "true"
spec:
  selector:
    matchLabels:
      app: erhudy-test-semicolon-every-odd-minute
      kairos-test: "true"
  template:
    metadata:
      labels:
        app: erhudy-test-semicolon-every-odd-minute
        kairos-test: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: erhudy-test
          image: alpine:latest
          command: ["sleep", "infinity"]